version: '3'

services:
  postgres-0:
    image: postgres:alpine
    container_name: postgres-0
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: talkshop0
    ports:
      - 5432:5432

  redis:
    image: redis:alpine
    container_name: redis-0
    ports:
      - 6379:6379

  create-db:
    image: postgres:alpine
    depends_on:
      - postgres-0
    environment:
      PGPASSWORD: postgres
    command: sh -c 'sleep 15 && createdb -h postgres-0 -U postgres talkshop0'