version: '3'

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: talkshop0
    ports:
      - 5432:5432
  api:
    build: 
      context: .
      target: development
      args:
        - NODE_ENV=development
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: npm run dev